# -*- coding: utf-8 -*-
"""dummy variables addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a61cR99e7jrDXTahbtiq40sMXyv0HUB-
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks/dissertation"

import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/dissertation")

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from typing import List, Tuple, Dict, Optional
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.outliers_influence import variance_inflation_factor
from company_insolvency_regression import build_df_master, add_lag_ols

df = pd.read_csv("national_merged.csv", parse_dates=["date"])
print(df.head())
print(df.columns)

df_master = build_df_master(df)
print(df_master.head())

model_gdp_lag24_no_binv, diag_gdp_lag24_no_binv, xcols_used12 = add_lag_ols(
    df=df_master,
    y_col="company_insolvency_rate_per_10k",
    base_x_cols=[
        "unemployment_rate", "gdp_rate",
        "gdp_rate_lag24","electricity_price_rate",
        "inflation_rate_lag12", "inflation_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used12)
print(model_gdp_lag24_no_binv.summary())
print(diag_gdp_lag24_no_binv)

final_lagged_model = model_gdp_lag24_no_binv
final_lagged_diag = diag_gdp_lag24_no_binv
final_lagged_xcols = xcols_used12

print(final_lagged_xcols)
print(final_lagged_model.summary())
print(final_lagged_diag)

# function to create dummies
def shock_dummy(df, start, end):
    start = pd.to_datetime(start)
    end = pd.to_datetime(end)
    return ((df["date"] >= start) & (df["date"] <= end)).astype("int")

# event dummies
df_master["brexit_transition_period"] = shock_dummy(df_master, "2020-01-01", "2021-01-01")
df_master ["brexit_year_after"] = shock_dummy(df_master, "2021-01-01", "2021-12-01")
df_master["covid_moratorium"] = shock_dummy(df_master, "2020-03-01", "2022-04-01")
df_master["energy_crisis"] = shock_dummy(df_master, "2021-10-01", "2025-02-01")

print(df_master[["brexit_transition_period", "brexit_year_after", "covid_moratorium","energy_crisis"]].head(40))

# my plot to see if they turn on off correctly
df_master.plot(x="date",
               y=["brexit_transition_period","brexit_year_after", "covid_moratorium","energy_crisis"],
               figsize=(10,4),
               title="event dummies over time")
plt.ylabel("dummy (1=active, 0=off)")
plt.show()

# my model plus dummies all together after full lag

final_predictors_comp_ins = ["unemployment_rate", "gdp_rate","gdp_rate_lag24",
                   "electricity_price_rate", "inflation_rate_lag12", "inflation_rate_lag24"]

shock_dummies = ["brexit_transition_period","brexit_year_after", "covid_moratorium",
                 "energy_crisis"]

X_cols = final_predictors_comp_ins + shock_dummies

model_with_dummies_main, diag_with_dummies_main, xcols_used_dummies_main = add_lag_ols(
    df=df_master,
    y_col="company_insolvency_rate_per_10k",
    base_x_cols=X_cols,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_main)
print(model_with_dummies_main.summary())
print(diag_with_dummies_main)

final_predictors_comp_ins2 = ["unemployment_rate", "gdp_rate","gdp_rate_lag24",
                              "electricity_price_rate", "inflation_rate_lag12", "inflation_rate_lag24"]
shock_dummies_2 = ["brexit_transition_period","brexit_year_after", "covid_moratorium"]
X_cols_2 = final_predictors_comp_ins2 + shock_dummies_2

model_with_dummies_main2, diag_with_dummies_main2, xcols_used_dummies_main2 = add_lag_ols(
    df=df_master,
    y_col="company_insolvency_rate_per_10k",
    base_x_cols=X_cols_2,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_main2)
print(model_with_dummies_main2.summary())
print(diag_with_dummies_main2)

final_predictors_comp_ins3 = ["gdp_rate","gdp_rate_lag24",
                              "electricity_price_rate", "inflation_rate_lag12", "inflation_rate_lag24"]
X_cols_3 = final_predictors_comp_ins3 + shock_dummies_2

model_with_dummies_main3, diag_with_dummies_main3, xcols_used_dummies_main3 = add_lag_ols(
    df=df_master,
    y_col="company_insolvency_rate_per_10k",
    base_x_cols=X_cols_3,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_main3)
print(model_with_dummies_main3.summary())
print(diag_with_dummies_main3)

final_predictors_comp_ins4 = ["unemployment_rate", "gdp_rate","gdp_rate_lag24",
                              "electricity_price_rate", "inflation_rate_lag12"]
X_cols_4 = final_predictors_comp_ins4 + shock_dummies_2

model_with_dummies_main4, diag_with_dummies_main4, xcols_used_dummies_main4 = add_lag_ols(
    df=df_master,
    y_col="company_insolvency_rate_per_10k",
    base_x_cols=X_cols_4,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_main4)
print(model_with_dummies_main4.summary())
print(diag_with_dummies_main4)

"""individual insolvencies dummies:

"""

final_predictors_indiv_ins=["inflation_rate", "unemployment_rate", "gdp_rate", "business_investment_rate", "business_investment_rate_lag24", "electricity_price_rate", "electricity_price_rate_lag12"]
X_cols2 = final_predictors_indiv_ins + shock_dummies

model_with_dummies_extension, diag_with_dummies_extension, xcols_used_dummies_ext = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=X_cols2,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_ext)
print(model_with_dummies_extension.summary())
print(diag_with_dummies_extension)

final_predictors_indiv_ins2=["unemployment_rate", "gdp_rate", "business_investment_rate", "business_investment_rate_lag24", "electricity_price_rate", "electricity_price_rate_lag12"]
X_cols3 = final_predictors_indiv_ins2 + shock_dummies

model_with_dummies_extension2, diag_with_dummies_extension2, xcols_used_dummies_ext2 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=X_cols3,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_ext2)
print(model_with_dummies_extension2.summary())
print(diag_with_dummies_extension2)

final_predictors_indiv_ins3=["unemployment_rate", "gdp_rate","business_investment_rate_lag24", "electricity_price_rate", "electricity_price_rate_lag12"]
X_cols4 = final_predictors_indiv_ins3 + shock_dummies

model_with_dummies_extension3, diag_with_dummies_extension3, xcols_used_dummies_ext3 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=X_cols4,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_ext3)
print(model_with_dummies_extension3.summary())
print(diag_with_dummies_extension3)

final_predictors_indiv_ins4=["unemployment_rate", "business_investment_rate","business_investment_rate_lag24", "electricity_price_rate", "electricity_price_rate_lag12"]
X_cols5 = final_predictors_indiv_ins4 + shock_dummies

model_with_dummies_extension4, diag_with_dummies_extension4, xcols_used_dummies_ext4 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=X_cols5,
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_dummies_ext4)
print(model_with_dummies_extension4.summary())
print(diag_with_dummies_extension4)