# -*- coding: utf-8 -*-
"""individual insolvency regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qx3LeM4Pd0R0UG4a2G5CjU3MIq_lTFBR
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks/dissertation"

import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/dissertation")

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from typing import List, Tuple, Dict, Optional
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.regression.linear_model import GLSAR
from company_insolvency_regression import baseline_ols, add_lag_ols, build_df_master

df = pd.read_csv("national_merged.csv", parse_dates=["date"])
print(df.head())
print(df.columns)

model, info = baseline_ols(
    df=df,
    y_col="individual_insolvency_rate_per_10k",
    x_cols=["inflation_rate", "unemployment_rate", "gdp_rate", "business_investment_rate", "electricity_price_rate", "regular_pay_rate"],
    date_col="date",
    assert_no_na=True,
    se_method="HAC",
    se_args={"maxlags":12},
    make_plots=True)

print(model.summary())
print(info["diagnostics"])

df_master = build_df_master(df)
print(df_master.head())

# checking correlation between variables to see why VIF could explode so much
df_master[["individual_insolvency_rate_per_10k","inflation_rate",
           "inflation_rate_lag12", "inflation_rate_lag24",
           "unemployment_rate", "unemployment_rate_lag12",
           "unemployment_rate_lag24", "gdp_rate", "gdp_rate_lag12",
           "gdp_rate_lag24","business_investment_rate",
           "business_investment_rate_lag12", "business_investment_rate_lag24",
           "electricity_price_rate", "electricity_price_rate_lag12",
           "electricity_price_rate_lag24", "regular_pay_rate",
           "regular_pay_rate_lag12", "regular_pay_rate_lag24"]].corr().round(3)

#model with all variables + inflation lag 12
model_infl_lag12, diag_infl_lag12, xcols_used = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate",
                 "unemployment_rate", "gdp_rate",
                 "business_investment_rate", "electricity_price_rate",
                 "regular_pay_rate", "inflation_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12}
)
print(xcols_used)
print(model_infl_lag12.summary())
print(diag_infl_lag12)

# checking model only for inflation that is lagged 12 month to see its behaviour on its own
model_infl_onlylag12, diag_infl_onlylag12, xcols_used2 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["unemployment_rate", "gdp_rate",
                 "business_investment_rate", "electricity_price_rate",
                 "regular_pay_rate", "inflation_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used2)
print(model_infl_onlylag12.summary())
print(diag_infl_onlylag12)

# checking model with all inittial variables + inflation lag 24
model_infl_lag24, diag_infl_lag24, xcols_used3 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate", "gdp_rate",
                 "business_investment_rate", "electricity_price_rate",
                 "regular_pay_rate", "inflation_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used3)
print(model_infl_lag24.summary())
print(diag_infl_lag24)

# checking model for inflation only with 24 lags as original inflation was insignifican in the model before
model_infl_onlylag24, diag_infl_onlylag24, xcols_used4 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["unemployment_rate", "gdp_rate",
                 "business_investment_rate", "electricity_price_rate",
                 "regular_pay_rate", "inflation_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used4)
print(model_infl_onlylag24.summary())
print(diag_infl_onlylag24)

#removed pay_rate to stabilise for concerningly high vif values and also pay became insignifican when adding both 12 and 24 month inflation variables
model_infl_no_pay, diag_infl_no_pay, xcols_used_ = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate","unemployment_rate", "gdp_rate",
                 "business_investment_rate", "electricity_price_rate",],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used_)
print(model_infl_no_pay.summary())
print(diag_infl_no_pay)

# checking model for all variables from model above (no pay_rate) + unemployment lag 12
model_unemp_lag12, diag_unemp_lag12, xcols_used5 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate","unemployment_rate", "unemployment_rate_lag12",
                 "gdp_rate", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used5)
print(model_unemp_lag12.summary())
print(diag_unemp_lag12)

model_unemp_onlylag12, diag_unemp_onlylag12, xcols_used6 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate_lag12",
                 "gdp_rate", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used6)
print(model_unemp_onlylag12.summary())
print(diag_unemp_onlylag12)

model_unemp_lag24, diag_unemp_lag24, xcols_used7 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate","unemployment_rate", "unemployment_rate_lag24",
                 "gdp_rate", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used7)
print(model_unemp_lag24.summary())
print(diag_unemp_lag24)

model_unemp_onlylag24, diag_unemp_onlylag24, xcols_used8 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate","unemployment_rate_lag24",
                 "gdp_rate", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used8)
print(model_unemp_onlylag24.summary())
print(diag_unemp_onlylag24)

model_gdp_lag12, diag_gdp_lag12, xcols_used9 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "gdp_rate_lag12", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used9)
print(model_gdp_lag12.summary())
print(diag_gdp_lag12)

model_gdp_only_lag12, diag_gdp_only_lag12, xcols_used10 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate_lag12", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used10)
print(model_gdp_only_lag12.summary())
print(diag_gdp_only_lag12)

model_gdp_lag24, diag_gdp_lag24, xcols_used11 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "gdp_rate_lag24", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used11)
print(model_gdp_lag24.summary())
print(diag_gdp_lag24)

model_gdp_only_lag24, diag_gdp_only_lag24, xcols_used12 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate_lag24", "business_investment_rate",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used12)
print(model_gdp_only_lag24.summary())
print(diag_gdp_only_lag24)

model_binv_lag12, diag_binv_lag12, xcols_used13 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate",
                 "business_investment_rate_lag12", "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used13)
print(model_binv_lag12.summary())
print(diag_binv_lag12)

model_binv_only_lag12, diag_binv_only_lag12, xcols_used14 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate_lag12",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used14)
print(model_binv_only_lag12.summary())
print(diag_binv_only_lag12)

model_binv_lag24, diag_binv_lag24, xcols_used15 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate",
                 "business_investment_rate_lag24", "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used15)
print(model_binv_lag24.summary())
print(diag_binv_lag24)

model_binv_only_lag24, diag_binv_only_lag24, xcols_used16 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate_lag24",
                 "electricity_price_rate"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used16)
print(model_binv_only_lag24.summary())
print(diag_binv_only_lag24)

model_electricity_lag12, diag_electricity_lag12, xcols_used17 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate",
                 "business_investment_rate_lag24",
                 "electricity_price_rate", "electricity_price_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used17)
print(model_electricity_lag12.summary())
print(diag_electricity_lag12)

model_electricity_only_lag12, diag_electricity_only_lag12, xcols_used18 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate",
                 "business_investment_rate_lag24",
                 "electricity_price_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used18)
print(model_electricity_only_lag12.summary())
print(diag_electricity_only_lag12)

model_electricity_lag24, diag_electricity_lag24, xcols_used19 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate", "business_investment_rate_lag24",
                 "electricity_price_rate", "electricity_price_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used19)
print(model_electricity_lag24.summary())
print(diag_electricity_lag24)

model_electricity_only_lag24, diag_electricity_only_lag24, xcols_used20 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate",
                 "business_investment_rate_lag24",
                 "electricity_price_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used20)
print(model_electricity_only_lag24.summary())
print(diag_electricity_only_lag24)

model_electricity_all, diag_electricity_all, xcols_used21 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate", "business_investment_rate_lag24",
                 "electricity_price_rate", "electricity_price_rate_lag12",
                 "electricity_price_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used21)
print(model_electricity_all.summary())
print(diag_electricity_all)

model_pay_lag12, diag_pay_lag12, xcols_used22 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate", "business_investment_rate_lag24",
                 "electricity_price_rate", "electricity_price_rate_lag12", "regular_pay_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used22)
print(model_pay_lag12.summary())
print(diag_pay_lag12)

model_pay_lag24, diag_pay_lag24, xcols_used23 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["inflation_rate", "unemployment_rate",
                 "gdp_rate", "business_investment_rate", "business_investment_rate_lag24",
                 "electricity_price_rate", "electricity_price_rate_lag12",
                 "regular_pay_rate_lag24"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})
print(xcols_used23)
print(model_pay_lag24.summary())
print(diag_pay_lag24)

model_final_dep_var, diag_final_dep_var, xcols_used_final_dep_var = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["individual_insolvency_rate_lag12",
                 "inflation_rate",
                 "unemployment_rate",
                 "gdp_rate",
                 "business_investment_rate",
                 "business_investment_rate_lag24",
                 "electricity_price_rate",
                 "electricity_price_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})

print(xcols_used_final_dep_var)
print(model_final_dep_var.summary())
print(diag_final_dep_var)

model_final_dep_var2, diag_final_dep_var2, xcols_used_final_dep_var2 = add_lag_ols(
    df=df_master,
    y_col="individual_insolvency_rate_per_10k",
    base_x_cols=["individual_insolvency_rate_lag1",
                 "inflation_rate",
                 "unemployment_rate",
                 "gdp_rate",
                 "business_investment_rate",
                 "business_investment_rate_lag24",
                 "electricity_price_rate",
                 "electricity_price_rate_lag12"],
    date_col="date",
    se_method="HAC",
    se_args={"maxlags": 12})

print(xcols_used_final_dep_var2)
print(model_final_dep_var2.summary())
print(diag_final_dep_var2)

final_lagged_model = model_electricity_lag12
final_lagged_diag = diag_electricity_lag12
final_lagged_xcols = xcols_used17

print(final_lagged_xcols)
print(final_lagged_model.summary())
print(final_lagged_diag)