# -*- coding: utf-8 -*-
"""merging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j--jA_8v2-MQeXOKzQDGwdLvYHZD7FiG
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks/dissertation"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import sys
from functools import reduce
from cleaning import clean_insolvency, clean_macro, plot_comp_insolvency
sys.path.append("/content/drive/MyDrive/Colab Notebooks/dissertation")

# cleaning national company insolvency data and individual insolvency data (for analysis after main implementation) - my dependent variable
company_insolvency = clean_insolvency(filepath="LR_series_insolvency.csv", insolvency_type="company")

individual_insolvency = clean_insolvency(filepath="LR_series_individual_insolvency.csv", insolvency_type="individual")

# cleaning each macroeconomic predictor using clean_macro() function from cleaning.py
inflation=clean_macro("inflation_cpih.csv",
                      date_col="date",
                      value_col="inflation_rate",
                      new_value_col_name="inflation_rate",
                      outfile="clean_inflation_rates.csv",
                      skiprows=8,
                      names=["date", "inflation_rate"],
                      start="2017-01-01")

unemployment=clean_macro("unemployment_sa.csv",
                         date_col="date",
                         value_col="unemployment_rate",
                         new_value_col_name="unemployment_rate",
                         outfile="clean_unemployment_rates.csv",
                         skiprows=8,
                         names=["date", "unemployment_rate"],
                         start="2017-01-01")

gdp=clean_macro("gdp_cva_sa.csv",
                date_col="date",
                value_col="gdp_rate",
                new_value_col_name="gdp_rate",
                outfile="clean_gdp_rates.csv",
                skiprows=9,
                names=["date", "gdp_rate"],
                frequency="Q",
                start="2017-01-01")

business_investment=clean_macro("business_investment.csv",
                                date_col="date", value_col="business_investment",
                                new_value_col_name="business_investment_rate",
                                outfile="clean_business_investment_rates.csv",
                                skiprows=4,
                                names=["date", "gfcf","business_investment","na", "na2", "na3", "na4"],
                                frequency="Q",
                                drop_missing=False,
                                start="2017-01-01",
                                calc_year_on_year=True)

electricity_prices=clean_macro("RPI-electricity.csv",
                               date_col="date",
                               value_col="electricity_price_rates",
                               new_value_col_name="electricity_price_rate",
                               outfile="clean_rpi_electricity.csv",
                               skiprows=9,
                               names=["date", "electricity_price_rates"],
                               start="2017-01-01")

weakly_earnings=clean_macro("average-weakly-earnings.csv",
                            date_col="date",
                            value_col="regular_pay",
                            new_value_col_name="regular_pay_rate",
                            outfile="clean_average_weakly_pay_rates.csv",
                            skiprows=8,
                            names=["date", "total_pay", "regular_pay"],
                            frequency="M",
                            calc_year_on_year=True,
                            start="2017-01-01")

# make sure all datasets to start at the first day of each month for consistency just in case
for df in [inflation, unemployment, gdp, business_investment, electricity_prices, weakly_earnings, company_insolvency, individual_insolvency]:
    df["date"] = pd.to_datetime(df["date"]) + pd.offsets.MonthBegin(0)

# merge all datasets on the "date" column
dfs = [inflation, unemployment, gdp, business_investment, electricity_prices, weakly_earnings, company_insolvency, individual_insolvency]
merged = reduce(lambda l, r: pd.merge(l, r, on="date", how="inner"), dfs)

# sorting
merged = merged.sort_values("date").reset_index(drop=True)
print(merged.head())
print("columns:", list(merged.columns))

merged.to_csv("national_merged.csv", index=False)
files.download("national_merged.csv")
merged.to_csv("/content/drive/MyDrive/Colab Notebooks/dissertation/national_merged.csv", index=False)

df = pd.read_csv("national_merged.csv", parse_dates=["date"])
print(df.head())
print(df.columns)

ins_plot=plot_comp_insolvency(df)